# Generated by: Asiful Mahfuze (asifulm)
#
# Copyright © Microsoft Corporation.  All Rights Reserved.
# This code released under the terms of the 
# Microsoft Public License (MS-PL, http://opensource.org/licenses/ms-pl.html.)
# Sample Code is provided for the purpose of illustration only and is not intended to be used in a production environment. 
# THIS SAMPLE CODE AND ANY RELATED INFORMATION ARE PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESSED OR IMPLIED, 
# INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A PARTICULAR PURPOSE. 
# We grant You a nonexclusive, royalty-free right to use and modify the Sample Code and to reproduce and distribute the object code form of the Sample Code, provided that. 
# You agree: 
# (i) to not use Our name, logo, or trademarks to market Your software product in which the Sample Code is embedded; 
# (ii) to include a valid copyright notice on Your software product in which the Sample Code is embedded; 
# and (iii) to indemnify, hold harmless, and defend Us and Our suppliers from and against any claims or lawsuits, including attorneys’ fees, that arise or result from the use or distribution of the Sample Code 

function Get-XmlTree
{
    param(
        [string] $xml
    )

    $nameDictionary = New-Object 'System.Collections.Generic.Dictionary[System.Xml.XmlNode, System.String]';

    $xmlDictionary = New-Object 'System.Collections.Generic.Dictionary[System.String, System.Xml.XmlNode]';
    $xmlDocument = New-Object System.Xml.XmlDocument;
    $xmlDocument.LoadXml($xml);
   
    $xmlQueue = New-Object System.Collections.Generic.Queue[System.Xml.XmlNode]
    $xmlQueue.Enqueue($xmlDocument.DocumentElement);
    
    $xmlDictionary[$xmlDocument.DocumentElement.Name] = $xmlDocument.DocumentElement;

    while($xmlQueue.Count -ne 0)
    {
        $element = $xmlQueue.Dequeue();
        $elementName = Get-NodeName $element;
        $elementPath =  $nameDictionary[$element];

        if ($nameDictionary.ContainsKey($element) -eq $false){
            $nameDictionary[$element] = [String]::Empty;
            $elementPath = Get-NodeName $element;
        }

        foreach ($child in $element.ChildNodes)
        {
            $childNodeName = Get-NodeName $child;
            $childPath =  [System.String]::Concat($elementPath, ">", $childNodeName);
            
            $xmlDictionary[$childPath] = $child;
            $nameDictionary[$child] = $childPath;
            $xmlQueue.Enqueue($child);
        }
    }

    return $xmlDictionary;
}

function Get-NodeName
{
    param 
    (
        [System.Xml.XmlNode] $node
    )

    if ($node.Attributes["Id"] -ne $null)
    {
        return $node.Attributes["Id"].Value;
    }
    return $node.Name;
}

function Merge-Xml
{
    param
    (
        [string] $xml1, 
        [string] $xml2
    )

    $tree1 = Get-XmlTree $xml1
    $tree2 = Get-XmlTree $xml2

    $newXmlDocument = ([System.Xml.XmlNode] $tree1["SiteMap"]).OwnerDocument;

    foreach ($key in $tree2.Keys)
    {
        if ($tree1.ContainsKey($key) -eq $false)
        {  
            $parent = $key.Substring(0, $key.LastIndexOf(">"));
            $tree1node = [System.Xml.XmlNode] $tree1[$parent];
            $tree2node = [System.Xml.XmlNode] $tree2[$key];

            if ($tree1node -ne $null)
            {
                $newElement = $newXmlDocument.CreateElement($tree2node.Name);
               
                for($index = 0; $index -lt $tree2node.Attributes.Count; $index++) 
                {
                    $attribute = [System.Xml.XmlAttribute] $tree2node.Attributes[$index];
                    $newAttribute = $newXmlDocument.CreateAttribute($attribute.Name);
                    $newAttribute.Value = $attribute.Value;
                    [void]$newElement.Attributes.Append($newAttribute);
                }

               [void]($tree1node.AppendChild($newElement));             
               $tree1[$key] = $newElement;
            }
        }
    }

    return $newXmlDocument.OuterXml;
}

function Publish-SiteMapXml
{
    param
    (
        [string] $sitemap, 
        [Microsoft.Xrm.Sdk.Client.OrganizationServiceProxy] $destinationProxy
    )
    
    $publishRequest= New-Object Microsoft.Crm.Sdk.Messages.PublishXmlRequest;
    $publishRequest.ParameterXml = "<ImportExportXml>$sitemap</ImportExportXml>";

    $destinationProxy.Execute($publishRequest);
}

# Source Organization 1
$conn1 = Connect-CrmOnlineDiscovery -InteractiveMode
# Source Organization 2
$conn2 = Connect-CrmOnlineDiscovery -InteractiveMode
# Target Organization
$conn3 = Connect-CrmOnlineDiscovery -InteractiveMode

# Get Sitemap from source organizations
$sitemap1 = (Get-CrmRecords -conn $conn1 -EntityLogicalName sitemap -Fields sitemapxml).CrmRecords[0].sitemapxml
$sitemap2 = (Get-CrmRecords -conn $conn2 -EntityLogicalName sitemap -Fields sitemapxml).CrmRecords[0].sitemapxml
# Merge Sitemap
$sitemap3 = Merge-Xml $sitemap1 $sitemap2

Write-Host "Site Map 1";
Write-Host $sitemap1;
      
Write-Host "Site Map 2";
Write-Host $sitemap2;
      
Write-Host "Site Map 3";
Write-Host $sitemap3;

# Publish merged sitemap to target organization
Publish-SiteMapXml $sitemap3 $conn3.OrganizationServiceProxy
# Get published sitemap and display
$publishedsitemap = (Get-CrmRecords -conn $conn3 -EntityLogicalName sitemap -Fields sitemapxml).CrmRecords[0].sitemapxml
Write-Host $publishedsitemap
